// Generated by Web Inormatics and Mapping on <%= (new Date).toISOString().split('T')[0] %> using <%= generatorInfo.name %> <%= generatorInfo.version %>

$( document ).ready(function() {

	//create map
	app.map = L.map('mapDiv');

	//basemap
	app.baseMapLayer = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}', {
		attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ',
		maxZoom: 16
	}).addTo(app.map);

	//set initial view
	app.map.setView([app.mapY, app.mapX], app.zoomLevel);
	
	/*  START EVENT HANDLERS */
	$('#mobile-main-menu').click(function() {
		$('body').toggleClass('isOpenMenu');
	});

	$('.basemapBtn').click(function() {
		$('.basemapBtn').removeClass('slick-btn-selection');
		$(this).addClass('slick-btn-selection');
		var baseMap = this.id.replace('btn','');
		setBasemap(baseMap);
	});

	$('#aboutButton').click(function() {
		$('#aboutModal').modal('show');
	});	

	/*  END EVENT HANDLERS */
});

function setBasemap(baseMap) {

	switch (baseMap) {
		case 'Streets': baseMap = 'Streets'; break;
		case 'Satellite': baseMap = 'Imagery'; break;
		case 'Topo': baseMap = 'Topographic'; break;
		case 'Terrain': baseMap = 'Terrain'; break;
		case 'Gray': baseMap = 'Gray'; break;
		case 'NatGeo': baseMap = 'NationalGeographic'; break;
	}

	if (app.baseMapLayer) app.map.removeLayer(app.baseMapLayer);
	app.baseMapLayer = L.esri.basemapLayer(baseMap);
	app.map.addLayer(app.baseMapLayer);
	if (app.baseMapLayerLabels) app.map.removeLayer(app.baseMapLayerLabels);
	if (baseMap === 'Gray' || baseMap === 'Imagery' || baseMap === 'Terrain') {
		app.baseMapLayerLabels = L.esri.basemapLayer(baseMap + 'Labels');
		app.map.addLayer(app.baseMapLayerLabels);
	}
}
