// Generated by Web Inormatics and Mapping on <%= (new Date).toISOString().split('T')[0] %> using <%= generatorInfo.name %> <%= generatorInfo.version %>

$(document).ready(function () {

    // User Guide Modal
    $('#userGuideButton').click(function () {
        $('#userGuideModal').modal('show');
    });

    // FAQ Modal
    $('#faqButton').click(function () {
        $('#faqModal').modal('show');
    });

    // FAQ Modal controls.
    $('#faq1header').click(function () { $('#faq1body').slideToggle(250); });
    $('#faq2header').click(function () { $('#faq2body').slideToggle(250); });
    $('#faq3header').click(function () { $('#faq3body').slideToggle(250); });
    $('#faq4header').click(function () { $('#faq4body').slideToggle(250); });
    $('#faq5header').click(function () { $('#faq5body').slideToggle(250); });
    $('#faq6header').click(function () { $('#faq6body').slideToggle(250); });
    $('#faq7header').click(function () { $('#faq7body').slideToggle(250); });
    $('#faq8header').click(function () { $('#faq8body').slideToggle(250); });
    $('#faq9header').click(function () { $('#faq9body').slideToggle(250); });
    $('#faq10header').click(function () { $('#faq10body').slideToggle(250); });
    $('#faq11header').click(function () { $('#faq11body').slideToggle(250); });
    $('#faq12header').click(function () { $('#faq12body').slideToggle(250); });
    $('#faq13header').click(function () { $('#faq13body').slideToggle(250); });
    $('#faq14header').click(function () { $('#faq14body').slideToggle(250); });
    $('#faq15header').click(function () { $('#faq15body').slideToggle(250); });
    $('#faq16header').click(function () { $('#faq16body').slideToggle(250); });
    $('#faq17header').click(function () { $('#faq17body').slideToggle(250); });
    $('#faq18header').click(function () { $('#faq18body').slideToggle(250); });
    $('#faq19header').click(function () { $('#faq19body').slideToggle(250); });
    $('#faq20header').click(function () { $('#faq20body').slideToggle(250); });
    $('#faq21header').click(function () { $('#faq21body').slideToggle(250); });
    $('#faq22header').click(function () { $('#faq22body').slideToggle(250); });
    $('#faq23header').click(function () { $('#faq23body').slideToggle(250); });
    $('#faq24header').click(function () { $('#faq24body').slideToggle(250); });
    $('#faq25header').click(function () { $('#faq25body').slideToggle(250); });
    $('#faq26header').click(function () { $('#faq26body').slideToggle(250); });
    $('#faq27header').click(function () { $('#faq27body').slideToggle(250); });
    $('#faq28header').click(function () { $('#faq28body').slideToggle(250); });

    // Rotating arrows when FAQ is clicked
    $("#faq1header").click(function () {
        if ($("#angle1").css("transform") == 'none') {
            $("#angle1").css("transform", "rotate(90deg)");
        } else {
            $("#angle1").css("transform", "");
        }
    });
    $("#faq2header").click(function () {
        //alert($( this ).css( "transform" ));
        if ($("#angle2").css("transform") == 'none') {
            $("#angle2").css("transform", "rotate(90deg)");
        } else {
            $("#angle2").css("transform", "");
        }
    });
    $("#faq3header").click(function () {
        //alert($( this ).css( "transform" ));
        if ($("#angle3").css("transform") == 'none') {
            $("#angle3").css("transform", "rotate(90deg)");
        } else {
            $("#angle3").css("transform", "");
        }
    });
    $("#faq4header").click(function () {
        //alert($( this ).css( "transform" ));
        if ($("#angle4").css("transform") == 'none') {
            $("#angle4").css("transform", "rotate(90deg)");
        } else {
            $("#angle4").css("transform", "");
        }
    });
    $("#faq5header").click(function () {
        //alert($( this ).css( "transform" ));
        if ($("#angle5").css("transform") == 'none') {
            $("#angle5").css("transform", "rotate(90deg)");
        } else {
            $("#angle5").css("transform", "");
        }
    });
    $("#faq6header").click(function () {
        //alert($( this ).css( "transform" ));
        if ($("#angle6").css("transform") == 'none') {
            $("#angle6").css("transform", "rotate(90deg)");
        } else {
            $("#angle6").css("transform", "");
        }
    });
    $("#faq7header").click(function () {
        //alert($( this ).css( "transform" ));
        if ($("#angle7").css("transform") == 'none') {
            $("#angle7").css("transform", "rotate(90deg)");
        } else {
            $("#angle7").css("transform", "");
        }
    });
    $("#faq8header").click(function () {
        //alert($( this ).css( "transform" ));
        if ($("#angle8").css("transform") == 'none') {
            $("#angle8").css("transform", "rotate(90deg)");
        } else {
            $("#angle8").css("transform", "");
        }
    });
    $("#faq9header").click(function () {
        //alert($( this ).css( "transform" ));
        if ($("#angle9").css("transform") == 'none') {
            $("#angle9").css("transform", "rotate(90deg)");
        } else {
            $("#angle9").css("transform", "");
        }
    });
    $("#faq10header").click(function () {
        //alert($( this ).css( "transform" ));
        if ($("#angle10").css("transform") == 'none') {
            $("#angle10").css("transform", "rotate(90deg)");
        } else {
            $("#angle10").css("transform", "");
        }
    });
});
