// Generated by Web Inormatics and Mapping on <%= (new Date).toISOString().split('T')[0] %> using <%= generatorInfo.name %> <%= generatorInfo.version %>

$( document ).ready(function() {

// User Guide Modal
    $('#userGuideButton').click(function(){
        $('#userGuideModal').modal('show');
    });
});
