// Generated by Web Inormatics and Mapping on <%= (new Date).toISOString().split('T')[0] %> using <%= generatorInfo.name %> <%= generatorInfo.version %>

$( document ).ready(function() {

	//create map
	app.map = L.map('mapDiv');

	//basemap
	app.baseMapLayer = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}', {
		attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ',
		maxZoom: 16
	}).addTo(app.map);

	//set initial view
	app.map.setView([app.mapY, app.mapX], app.zoomLevel);

	//set app version
	$('#aboutModalTitle').append(' <small>v' + app.version + '</small>');

	// USGS Search
	search_api.create( "geosearch", {
			on_result: function(o) {
				// what to do when a location is found
				// o.result is geojson point feature of location with properties
				app.map
					.fitBounds([ // zoom to location
						[ o.result.properties.LatMin, o.result.properties.LonMin ],
						[ o.result.properties.LatMax, o.result.properties.LonMax ]
					])
					$("#geosearchModal").modal('hide');
		},
		
			"include_usgs_sw": true,
			"include_usgs_gw": true,
			"include_usgs_sp": true,
			"include_usgs_at": true,
			"include_usgs_ot": true,
			"include_huc2": true,
			"include_huc4": true,
			"include_huc6": true,
			"include_huc8": true,
			"include_huc10": true,
			"include_huc12": true,
		});
	
	/*  START EVENT HANDLERS */
	$('#mobile-main-menu').click(function() {
		$('body').toggleClass('isOpenMenu');
	});

	$('.basemapBtn').click(function() {
		$('.basemapBtn').removeClass('slick-btn-selection');
		$(this).addClass('slick-btn-selection');
		var baseMap = this.id.replace('btn','');
		setBasemap(baseMap);
	});

	// geosearch modal
    $('#geosearchButton').click(function() {
		$('#geosearchModal').modal('show');
	});

	// about modal
	$('#aboutButton').click(function() {
		$('#aboutModal').modal('show');
	});	

	/*  END EVENT HANDLERS */
});

function setBasemap(baseMap) {

	switch (baseMap) {
		case 'Streets': baseMap = 'Streets'; break;
		case 'Satellite': baseMap = 'Imagery'; break;
		case 'Topo': baseMap = 'Topographic'; break;
		case 'Terrain': baseMap = 'Terrain'; break;
		case 'Gray': baseMap = 'Gray'; break;
		case 'NatGeo': baseMap = 'NationalGeographic'; break;
	}

	if (app.baseMapLayer) app.map.removeLayer(app.baseMapLayer);
	app.baseMapLayer = L.esri.basemapLayer(baseMap);
	app.map.addLayer(app.baseMapLayer);
	if (app.baseMapLayerLabels) app.map.removeLayer(app.baseMapLayerLabels);
	if (baseMap === 'Gray' || baseMap === 'Imagery' || baseMap === 'Terrain') {
		app.baseMapLayerLabels = L.esri.basemapLayer(baseMap + 'Labels');
		app.map.addLayer(app.baseMapLayerLabels);
	}
}
