// Generated by Web Inormatics and Mapping on <%= (new Date).toISOString().split('T')[0] %> using <%= generatorInfo.name %> <%= generatorInfo.version %>

require(['esri/map', 'dojo/domReady!'], function(Map) {
    app.map = new Map("mapDiv", {
        basemap: "gray",  //For full list of pre-defined basemaps, navigate to http://arcg.is/1JVo6Wd
        center: [app.mapX, app.mapY], // longitude, latitude
        zoom: app.zoomLevel
    });

    //basemap toggles
    $('#btnStreets').click(function() {
        app.map.setBasemap('streets');
    });
    $('#btnSatellite').click(function() {
        app.map.setBasemap('satellite');
    });
    $('#btnTopo').click(function() {
        app.map.setBasemap('topo');
    });
    $('#btnTerrain').click(function() {
        app.map.setBasemap('terrain');
    });
    $('#btnGray').click(function() {
        app.map.setBasemap('gray');
    });
    $('#btnNatGeo').click(function() {
        app.map.setBasemap('national-geographic');
    });

    //mobile menu toggle
    $('#mobile-main-menu').click(function() {
		$('body').toggleClass('isOpenMenu');
	});

    //about modal toggle
    $('#aboutButton').click(function() {
		$('#aboutModal').modal('show');
	});	
});