// Generated by Web Inormatics and Mapping on <%= (new Date).toISOString().split('T')[0] %> using <%= generatorInfo.name %> <%= generatorInfo.version %>

var app = {};
app.version = '<%= appInfo %>';
app.mapX = '-97.0';
app.mapY = '40.0';
app.zoomLevel = 4;